name: "RSpec Report"
description: "A GitHub Action that report RSpec failures"
branding:
  icon: alert-triangle
  color: red
author: "aki77"
inputs:
  token:
    description: "Github token"
    required: false
    default: "${{ github.token }}"
  json-path:
    description: "JSON File path"
    required: true
  title:
    description: "Title for PR comment and build summary"
    default: "Test report"
    required: false
  comment:
    description: "Set this if want to comment report to pull request"
    default: "true"
    required: false
  profileTitle:
    description: "Title for slowest tests report"
    default: "Slowest examples"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
